### ISSUE TITLE
npm run build 失败

### ISSUE THREAD

**Issue by name-trouble** [umicro/uView2.0-doc#6]
docs\.vuepress\components\colorPicker.vue中的“/deep/”写法与package.json中指定的sass版本冲突，会导致编译失败（npm run serve是可以成功的）。改成::v-deep可用。希望master看到修复一下。

**Comment by BeiQiaoT** [comment]
> docs.vuepress\components\colorPicker.vue中的“/deep/”写法与package.json中指定的sass版本冲突，会导致编译失败（npm run serve是可以成功的）。改成::v-deep可用。希望master看到修复一下。

在切换sass版本时没注意到，已修复
